[2025-04-08T09:14:43.906+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T09:14:44.084+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script manual__2025-04-08T09:14:10.036800+00:00 [queued]>
[2025-04-08T09:14:44.103+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script manual__2025-04-08T09:14:10.036800+00:00 [queued]>
[2025-04-08T09:14:44.105+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-08T09:14:44.124+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_postgres_script> on 2025-04-08 09:14:10.036800+00:00
[2025-04-08T09:14:44.130+0000] {standard_task_runner.py:72} INFO - Started process 6870 to run task
[2025-04-08T09:14:44.134+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_postgres_script', 'manual__2025-04-08T09:14:10.036800+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp_kq56yll']
[2025-04-08T09:14:44.138+0000] {standard_task_runner.py:105} INFO - Job 241: Subtask run_postgres_script
[2025-04-08T09:14:44.194+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_postgres_script manual__2025-04-08T09:14:10.036800+00:00 [running]> on host 3c3c1f66214b
[2025-04-08T09:14:44.271+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_postgres_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T09:14:10.036800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T09:14:10.036800+00:00'
[2025-04-08T09:14:44.273+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-08T09:14:44.273+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-08T09:14:44.274+0000] {logging_mixin.py:190} INFO - Current task name:run_postgres_script state:running start_date:2025-04-08 09:14:44.086562+00:00
[2025-04-08T09:14:44.275+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-04-08T09:14:44.275+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T09:14:44.277+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-08T09:14:44.278+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/postgres.py']
[2025-04-08T09:14:44.288+0000] {subprocess.py:99} INFO - Output:
[2025-04-08T09:14:47.095+0000] {subprocess.py:106} INFO - 25/04/08 09:14:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-08T09:14:47.401+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-04-08T09:14:47.404+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-08T09:14:53.181+0000] {subprocess.py:106} INFO - 25/04/08 09:14:53 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
[2025-04-08T09:14:53.183+0000] {subprocess.py:106} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","date","time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-04-06','04:00',16.0,17.6,50,16.0,0.0,'Cloudy','//cdn.weatherapi.com/weather/64x64/day/119.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.184+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-04-08T09:14:53.186+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-04-08T09:14:53.187+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-04-08T09:14:53.189+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-04-08T09:14:53.191+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-04-08T09:14:53.193+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-04-08T09:14:53.199+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-04-08T09:14:53.200+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-04-08T09:14:53.202+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-04-08T09:14:53.203+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-04-08T09:14:53.204+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-04-08T09:14:53.206+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-04-08T09:14:53.209+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-04-08T09:14:53.211+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-04-08T09:14:53.218+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-04-08T09:14:53.224+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-04-08T09:14:53.228+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-04-08T09:14:53.230+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-04-08T09:14:53.232+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-04-08T09:14:53.234+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-04-08T09:14:53.236+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-04-08T09:14:53.240+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-08T09:14:53.242+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-08T09:14:53.243+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-08T09:14:53.244+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.246+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.
[2025-04-08T09:14:53.248+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-04-08T09:14:53.250+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-04-08T09:14:53.251+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-04-08T09:14:53.252+0000] {subprocess.py:106} INFO - 25/04/08 09:14:53 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","date","time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-04-06','04:00',16.0,17.6,50,16.0,0.0,'Cloudy','//cdn.weatherapi.com/weather/64x64/day/119.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.254+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-04-08T09:14:53.255+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-04-08T09:14:53.256+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-04-08T09:14:53.258+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-04-08T09:14:53.259+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-04-08T09:14:53.261+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-04-08T09:14:53.262+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-04-08T09:14:53.263+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-04-08T09:14:53.265+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-04-08T09:14:53.266+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-04-08T09:14:53.268+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-04-08T09:14:53.272+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-04-08T09:14:53.274+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-04-08T09:14:53.276+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-04-08T09:14:53.278+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-04-08T09:14:53.281+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-04-08T09:14:53.284+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-04-08T09:14:53.286+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-04-08T09:14:53.288+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-04-08T09:14:53.291+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-04-08T09:14:53.292+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-04-08T09:14:53.294+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-08T09:14:53.295+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-08T09:14:53.298+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-08T09:14:53.299+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.301+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.
[2025-04-08T09:14:53.302+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-04-08T09:14:53.303+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-04-08T09:14:53.305+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-04-08T09:14:53.306+0000] {subprocess.py:106} INFO - 
[2025-04-08T09:14:53.307+0000] {subprocess.py:106} INFO - 25/04/08 09:14:53 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
[2025-04-08T09:14:53.664+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+--------------------+
[2025-04-08T09:14:53.665+0000] {subprocess.py:106} INFO - |                city|      date| time|temperature|wind_kph|humidity|feelslike|precip_mm|         text|                icon|
[2025-04-08T09:14:53.666+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+--------------------+
[2025-04-08T09:14:53.667+0000] {subprocess.py:106} INFO - |               elche|2025-04-06|04:00|       16.0|    17.6|      50|     16.0|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.667+0000] {subprocess.py:106} INFO - |               elche|2025-04-06|09:00|       16.1|    13.1|      51|     16.1|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.668+0000] {subprocess.py:106} INFO - |               elche|2025-04-06|15:00|       24.6|    15.2|      25|     24.6|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.669+0000] {subprocess.py:106} INFO - |               elche|2025-04-06|22:00|       18.1|     0.4|      52|     18.1|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.670+0000] {subprocess.py:106} INFO - |              madrid|2025-04-06|04:00|        9.8|     2.9|      87|      9.8|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.671+0000] {subprocess.py:106} INFO - |              madrid|2025-04-06|09:00|        9.4|     3.3|      91|      9.4|      0.0| Mostly Clear|//cdn.weatherapi....|
[2025-04-08T09:14:53.672+0000] {subprocess.py:106} INFO - |              madrid|2025-04-06|15:00|       16.9|     2.5|      51|     16.9|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.673+0000] {subprocess.py:106} INFO - |              madrid|2025-04-06|22:00|       13.5|     7.0|      71|     13.5|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.674+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-06|04:00|       14.1|     9.4|      57|     14.1|      0.0|Partly Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.676+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-06|09:00|       15.6|     7.6|      50|     15.6|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.677+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-06|15:00|       22.8|    16.8|      30|     22.8|      0.0| Mostly Clear|//cdn.weatherapi....|
[2025-04-08T09:14:53.678+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-06|22:00|       16.9|     2.1|      56|     16.9|      0.0| Mostly Clear|//cdn.weatherapi....|
[2025-04-08T09:14:53.680+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-06|04:00|       15.1|    16.3|      61|     15.1|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.681+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-06|09:00|       14.8|    17.7|      64|     14.8|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.682+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-06|15:00|       21.6|    15.8|      52|     21.6|      0.0| Mostly Clear|//cdn.weatherapi....|
[2025-04-08T09:14:53.683+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-06|22:00|       16.7|     8.1|      62|     16.7|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.685+0000] {subprocess.py:106} INFO - |            valencia|2025-04-06|04:00|       13.7|    10.6|      63|     13.7|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.686+0000] {subprocess.py:106} INFO - |            valencia|2025-04-06|09:00|       13.4|    10.0|      65|     13.4|      0.0|Partly Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.689+0000] {subprocess.py:106} INFO - |            valencia|2025-04-06|15:00|       23.8|     8.1|      31|     23.8|      0.0|       Cloudy|//cdn.weatherapi....|
[2025-04-08T09:14:53.691+0000] {subprocess.py:106} INFO - |            valencia|2025-04-06|22:00|       17.7|     3.6|      60|     17.7|      0.0|        Sunny|//cdn.weatherapi....|
[2025-04-08T09:14:53.692+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+-------------+--------------------+
[2025-04-08T09:14:53.693+0000] {subprocess.py:106} INFO - 
[2025-04-08T09:14:53.694+0000] {subprocess.py:106} INFO - Error: An error occurred while calling o43.save.
[2025-04-08T09:14:53.695+0000] {subprocess.py:106} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","date","time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-04-06','04:00',16.0,17.6,50,16.0,0.0,'Cloudy','//cdn.weatherapi.com/weather/64x64/day/119.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.697+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-04-08T09:14:53.698+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-04-08T09:14:53.699+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-04-08T09:14:53.700+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-04-08T09:14:53.701+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-04-08T09:14:53.702+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-04-08T09:14:53.703+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-04-08T09:14:53.705+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-04-08T09:14:53.706+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-04-08T09:14:53.707+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-04-08T09:14:53.708+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-04-08T09:14:53.709+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-04-08T09:14:53.714+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-04-08T09:14:53.715+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-04-08T09:14:53.716+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-04-08T09:14:53.717+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-04-08T09:14:53.719+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-04-08T09:14:53.720+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-04-08T09:14:53.721+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-04-08T09:14:53.722+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-04-08T09:14:53.723+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-04-08T09:14:53.724+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-08T09:14:53.725+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-08T09:14:53.726+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-08T09:14:53.727+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.727+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.
[2025-04-08T09:14:53.728+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-04-08T09:14:53.729+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-04-08T09:14:53.731+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-04-08T09:14:53.731+0000] {subprocess.py:106} INFO - 
[2025-04-08T09:14:53.732+0000] {subprocess.py:106} INFO - Driver stacktrace:
[2025-04-08T09:14:53.733+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-04-08T09:14:53.734+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-04-08T09:14:53.734+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-04-08T09:14:53.735+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-04-08T09:14:53.736+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-04-08T09:14:53.736+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-04-08T09:14:53.737+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-04-08T09:14:53.738+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-04-08T09:14:53.738+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-04-08T09:14:53.739+0000] {subprocess.py:106} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-04-08T09:14:53.739+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-04-08T09:14:53.740+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-04-08T09:14:53.741+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-04-08T09:14:53.741+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-04-08T09:14:53.742+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-04-08T09:14:53.743+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-04-08T09:14:53.743+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-04-08T09:14:53.744+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-04-08T09:14:53.744+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-04-08T09:14:53.745+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2458)
[2025-04-08T09:14:53.746+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1039)
[2025-04-08T09:14:53.747+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-04-08T09:14:53.747+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-04-08T09:14:53.748+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2025-04-08T09:14:53.749+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1037)
[2025-04-08T09:14:53.749+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:3516)
[2025-04-08T09:14:53.750+0000] {subprocess.py:106} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-08T09:14:53.750+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:4310)
[2025-04-08T09:14:53.751+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-04-08T09:14:53.751+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-04-08T09:14:53.752+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-04-08T09:14:53.752+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-04-08T09:14:53.753+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-04-08T09:14:53.753+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:4308)
[2025-04-08T09:14:53.754+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:3516)
[2025-04-08T09:14:53.754+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:903)
[2025-04-08T09:14:53.755+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:70)
[2025-04-08T09:14:53.756+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[2025-04-08T09:14:53.756+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
[2025-04-08T09:14:53.757+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
[2025-04-08T09:14:53.757+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
[2025-04-08T09:14:53.758+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-04-08T09:14:53.758+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-04-08T09:14:53.759+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-04-08T09:14:53.759+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-04-08T09:14:53.760+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-04-08T09:14:53.760+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-04-08T09:14:53.761+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-04-08T09:14:53.762+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-04-08T09:14:53.762+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-04-08T09:14:53.763+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-04-08T09:14:53.764+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-04-08T09:14:53.765+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-04-08T09:14:53.765+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-04-08T09:14:53.766+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-04-08T09:14:53.766+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-04-08T09:14:53.767+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-04-08T09:14:53.768+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-04-08T09:14:53.768+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-04-08T09:14:53.769+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-04-08T09:14:53.769+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-04-08T09:14:53.770+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-04-08T09:14:53.770+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-04-08T09:14:53.771+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-04-08T09:14:53.771+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-04-08T09:14:53.772+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
[2025-04-08T09:14:53.772+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-04-08T09:14:53.773+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-04-08T09:14:53.774+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-04-08T09:14:53.774+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-04-08T09:14:53.775+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-04-08T09:14:53.775+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-08T09:14:53.776+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-04-08T09:14:53.776+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-04-08T09:14:53.777+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-04-08T09:14:53.777+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-08T09:14:53.778+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-08T09:14:53.778+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-08T09:14:53.779+0000] {subprocess.py:106} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","date","time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-04-06','04:00',16.0,17.6,50,16.0,0.0,'Cloudy','//cdn.weatherapi.com/weather/64x64/day/119.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.780+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-04-08T09:14:53.781+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-04-08T09:14:53.782+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-04-08T09:14:53.782+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-04-08T09:14:53.783+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-04-08T09:14:53.783+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-04-08T09:14:53.784+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-04-08T09:14:53.784+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-04-08T09:14:53.785+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-04-08T09:14:53.785+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-04-08T09:14:53.786+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-04-08T09:14:53.787+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-04-08T09:14:53.787+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-04-08T09:14:53.788+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-04-08T09:14:53.788+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-04-08T09:14:53.789+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-04-08T09:14:53.789+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-04-08T09:14:53.790+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-04-08T09:14:53.790+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-04-08T09:14:53.791+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-04-08T09:14:53.792+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-04-08T09:14:53.792+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-08T09:14:53.793+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-08T09:14:53.793+0000] {subprocess.py:106} INFO - 	... 1 more
[2025-04-08T09:14:53.794+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-04-08T09:14:53.794+0000] {subprocess.py:106} INFO -   Detail: Key (city, date, "time")=(elche, 2025-04-06, 04:00) already exists.
[2025-04-08T09:14:53.795+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-04-08T09:14:53.796+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-04-08T09:14:53.797+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-04-08T09:14:54.001+0000] {subprocess.py:106} INFO - 
[2025-04-08T09:14:54.485+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-08T09:14:54.505+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T09:14:54.507+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_postgres_script, run_id=manual__2025-04-08T09:14:10.036800+00:00, execution_date=20250408T091410, start_date=20250408T091444, end_date=20250408T091454
[2025-04-08T09:14:54.526+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-08T09:14:54.527+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-08T09:14:54.528+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-04-08 09:14:10.054893+00:00
[2025-04-08T09:14:54.529+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-04-08T09:14:54.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T09:14:54.580+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-08T09:14:54.582+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
